# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc_m_docmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_area', models.CharField(max_length=10)),
                ('doc_subbarea', models.CharField(blank=True, max_length=10)),
                ('doc_tag', models.CharField(blank=True, max_length=30)),
                ('doc_sub', models.CharField(max_length=100)),
                ('doc_public', models.TextField()),
            ],
        ),
    ]
