# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc_m_docmaster',
            old_name='doc_subbarea',
            new_name='doc_subarea',
        ),
    ]
