# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20171202_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc_m_docmaster',
            name='doc_private',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doc_m_docmaster',
            name='doc_ref',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doc_m_docmaster',
            name='doc_register',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doc_m_docmaster',
            name='doc_public',
            field=models.TextField(blank=True),
        ),
    ]
