# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20171210_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc_m_files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200)),
                ('file_data', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='\\docs')),
            ],
        ),
    ]
