# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_doc_m_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_m_files',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
