# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_auto_20171215_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_m_files',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
