# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_auto_20171215_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_m_files',
            name='file_data',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='ITBones'),
        ),
    ]
