# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_auto_20171216_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_m_files',
            name='file_data',
            field=models.FileField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='ITBones_Public'),
        ),
        migrations.AlterField(
            model_name='doc_m_files',
            name='file_data_public',
            field=models.FileField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='ITBones_Private'),
        ),
    ]
