# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nse_m_stocklist',
            name='plfinal',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
