# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0002_auto_20171124_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nse_m_stocklist',
            name='buydate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nse_m_stocklist',
            name='plfinal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nse_m_stocklist',
            name='selldate',
            field=models.DateField(),
        ),
    ]
