# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0003_auto_20171124_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nse_m_stocklist',
            name='selldate',
            field=models.DateField(blank=True),
        ),
    ]
