# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0004_auto_20171124_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nse_m_stocklist',
            name='buydate',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='nse_m_stocklist',
            name='selldate',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
