# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0007_auto_20171124_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='nse_m_stocklist',
            name='sellqty',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
