# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0008_nse_m_stocklist_sellqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nse_m_stocklist',
            name='buyprice',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nse_m_stocklist',
            name='buyqty',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nse_m_stocklist',
            name='notval1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nse_m_stocklist',
            name='notval2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nse_m_stocklist',
            name='notval3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='nse_m_stocklist',
            name='stock_desc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
