# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0009_auto_20171128_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='nse_m_summarysheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=30)),
                ('avgbuyprice', models.CharField(blank=True, max_length=10)),
                ('totbuyqty', models.CharField(blank=True, max_length=10)),
                ('totbuyvalue', models.CharField(blank=True, max_length=10)),
                ('currprice', models.CharField(blank=True, max_length=10)),
                ('currvalue', models.CharField(blank=True, max_length=10)),
                ('realpos', models.CharField(blank=True, max_length=10)),
                ('stock_type', models.CharField(blank=True, max_length=2)),
            ],
        ),
    ]
