# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0010_nse_m_summarysheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='nse_m_stocknews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=30)),
                ('notedate', models.DateField(null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
